### ISSUE TITLE
请问是否支持windows？ 有编译、使用教程吗？

### ISSUE THREAD

**Issue by mingyuejingque** [yzsme/kcpvpn#2]
如题， 请教windows下是否支持？

**Comment by yzslab** [comment]
你好，仅支持Linux，编译与使用教程在项目的README中已较为详细地描述。

Sincerely,
Zhensheng Yuan
________________________________
发件人: 明月惊鹊 <notifications@github.com>
发送时间: Thursday, April 2, 2020 3:52:32 PM
收件人: yzsme/kcpvpn <kcpvpn@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [yzsme/kcpvpn] 请问是否支持windows？ 有编译、使用教程吗？ (#2)


如题， 请教windows下是否支持？

―

**Comment by mingyuejingque** [comment]
感谢指导！
